using Microsoft.EntityFrameworkCore;
using VbMerchant.Data;
using VbMerchant.Data.Entities;
using VbMerchant.Repositories;

namespace VbMerchant.Services;

public class AuthSeedService
{
    private const string SeedSectionName = "SeedUser";

    private readonly IUserRepository _userRepository;
    private readonly AppDbContext _dbContext;
    private readonly IConfiguration _configuration;
    private readonly ILogger<AuthSeedService> _logger;

    public AuthSeedService(
        IUserRepository userRepository,
        AppDbContext dbContext,
        IConfiguration configuration,
        ILogger<AuthSeedService> logger)
    {
        _userRepository = userRepository;
        _dbContext = dbContext;
        _configuration = configuration;
        _logger = logger;
    }

    public async Task SeedAsync(CancellationToken cancellationToken = default)
    {
        var seedSection = _configuration.GetSection(SeedSectionName);
        if (!seedSection.GetValue<bool>("Enabled"))
        {
            return;
        }

        await EnsureUserTableAsync(cancellationToken);

        var email = NormalizeEmail(seedSection["Email"]);
        var password = seedSection["Password"]?.Trim();
        var fullName = seedSection["FullName"]?.Trim();
        var role = seedSection["Role"]?.Trim();

        if (string.IsNullOrWhiteSpace(email) || string.IsNullOrWhiteSpace(password))
        {
            _logger.LogWarning(
                "{SectionName} etkin ancak Email veya Password yapılandırması eksik.",
                SeedSectionName);
            return;
        }

        fullName = string.IsNullOrWhiteSpace(fullName) ? "Test Admin" : fullName;
        role = string.IsNullOrWhiteSpace(role) ? "Admin" : role;

        var kullanici = await _userRepository.GetByEmailAsync(email, cancellationToken);
        var passwordHash = AuthService.SifreHashle(password);

        if (kullanici is null)
        {
            kullanici = new Kullanicilar
            {
                AdSoyad = fullName,
                Email = email,
                SifreHash = passwordHash,
                Rol = role,
                IsActive = true,
                OlusturmaTarihi = DateTime.Now
            };

            await _userRepository.AddAsync(kullanici, cancellationToken);
            await _userRepository.SaveChangesAsync(cancellationToken);

            _logger.LogInformation("Seed kullanıcısı oluşturuldu: {Email}", email);
            return;
        }

        var hasChanges = false;

        if (!string.Equals(kullanici.AdSoyad, fullName, StringComparison.Ordinal))
        {
            kullanici.AdSoyad = fullName;
            hasChanges = true;
        }

        if (!string.Equals(kullanici.Email, email, StringComparison.Ordinal))
        {
            kullanici.Email = email;
            hasChanges = true;
        }

        if (!AuthService.SifreDogrula(password, kullanici.SifreHash))
        {
            kullanici.SifreHash = passwordHash;
            hasChanges = true;
        }

        if (!string.Equals(kullanici.Rol, role, StringComparison.Ordinal))
        {
            kullanici.Rol = role;
            hasChanges = true;
        }

        if (!kullanici.IsActive)
        {
            kullanici.IsActive = true;
            hasChanges = true;
        }

        if (hasChanges)
        {
            await _userRepository.SaveChangesAsync(cancellationToken);
            _logger.LogInformation("Seed kullanıcısı güncellendi: {Email}", email);
        }
    }

    private Task EnsureUserTableAsync(CancellationToken cancellationToken)
    {
        return _dbContext.Database.ExecuteSqlRawAsync(
            """
            create table if not exists public.kullanicilar
            (
                id integer generated by default as identity primary key,
                ad_soyad varchar(100) not null,
                email varchar(150) not null,
                sifre_hash varchar(500) not null,
                rol varchar(50) not null default 'User',
                is_active boolean not null default true,
                olusturma_tarihi timestamp without time zone not null default current_timestamp,
                son_giris_tarihi timestamp without time zone null,
                constraint uq_kullanicilar_email unique (email)
            );
            """,
            cancellationToken);
    }

    private static string? NormalizeEmail(string? email)
    {
        return string.IsNullOrWhiteSpace(email)
            ? null
            : email.Trim().ToLowerInvariant();
    }
}
